Repository JeongHunMoon/SK-C-C-USA-GHOST-OFFICIAL, pull requests merged in 2024-01, with the labels that each got.

#35 feat/31- Add test case code
  src/test/java/GHOST/sk_ghost/controller/HomeTest.java
Labels: bug, test

#37 refac/36-Prepare for v1 presentation
  src/main/resources/application.properties
  src/main/resources/static/JavaScript/loginOPWithKakao.js
  src/main/resources/static/JavaScript/questionFunction.js
Labels: distribution, refactoring

#38 Dev
  build.gradle
  src/main/java/GHOST/sk_ghost/config/JasyptConfig.java
  src/main/resources/application.properties
  src/main/resources/static/JavaScript/loginOPWithKakao.js
  src/main/resources/static/JavaScript/questionFunction.js
  src/test/java/GHOST/sk_ghost/SkGhostApplicationTests.java
  src/test/java/GHOST/sk_ghost/controller/HomeTest.java
Labels: New, distribution, test

#44 feat/42-Complete creating main page connedted into db.
  src/main/java/GHOST/sk_ghost/controller/Home.java
  src/main/java/GHOST/sk_ghost/dao/V1Dao.java
  src/main/java/GHOST/sk_ghost/service/V1service.java
  src/main/resources/sqlmapper/V1sql.xml
  src/main/resources/static/JavaScript/adminDateSearch.js
  src/main/resources/static/JavaScript/imageModal.js
  src/main/resources/static/JavaScript/scheduleCard.js
  src/main/resources/static/css/admin/admin.css
  src/main/resources/static/css/login/login.css
  src/main/resources/templates/home/admin.html
Labels: enhancement, New

#55 feat/51-enhance
  src/main/resources/static/JavaScript/createCardStored.js
  src/main/resources/static/css/admin/admin.css
  src/main/resources/static/css/admin/newAdmin.css
  src/main/resources/static/css/init.css
  src/main/resources/templates/home/admin.html
  src/main/resources/templates/home/newSchedule.html
Labels: enhancement, New, refactoring

#56 feat/54-DB-validation-for-typo
  src/main/java/GHOST/sk_ghost/controller/Home.java
  src/main/java/GHOST/sk_ghost/dao/V1Dao.java
  src/main/java/GHOST/sk_ghost/service/V1service.java
  src/main/resources/sqlmapper/V1sql.xml
  src/main/resources/static/JavaScript/createSchedule.js
  src/main/resources/static/JavaScript/createScheduleCard.js
  src/main/resources/templates/home/create.html
Labels: bug, enhancement, New

#60 Feat/57 new
  src/main/java/GHOST/sk_ghost/controller/Admin.java
  src/main/java/GHOST/sk_ghost/controller/Home.java
  src/main/java/GHOST/sk_ghost/dao/V1Dao.java
  src/main/java/GHOST/sk_ghost/service/V1service.java
  src/main/resources/sqlmapper/V1sql.xml
  src/main/resources/static/JavaScript/createCardStored.js
  src/main/resources/static/JavaScript/newBtn.js
  src/main/resources/static/css/admin/newAdmin.css
  src/main/resources/templates/home/newSchedule.html
Labels: enhancement

#65 feat/62-enhance
  src/main/java/GHOST/sk_ghost/controller/Admin.java
  src/main/resources/static/JavaScript/savedwithSession.js
  src/main/resources/templates/home/newSchedule.html
Labels: enhancement, refactoring, test

#69 feat/68-enhance
  build.gradle
  src/main/java/GHOST/sk_ghost/controller/Admin.java
  src/main/java/GHOST/sk_ghost/controller/Home.java
  src/main/resources/static/JavaScript/createCardStored.js
  src/main/resources/static/JavaScript/createSchedule.js
  src/main/resources/static/JavaScript/createScheduleCard.js
  src/main/resources/static/JavaScript/loginWithKakaoForAdmin.js
  src/main/resources/static/JavaScript/newBtn.js
  src/main/resources/static/JavaScript/newScheduleFunction.js
  src/main/resources/static/JavaScript/scheduleCard.js
  src/main/resources/static/css/admin/admin.css
  src/main/resources/static/css/admin/newAdmin.css
  src/main/resources/templates/home/400.html
  src/main/resources/templates/home/404.html
  src/main/resources/templates/home/admin.html
  src/main/resources/templates/home/create.html
  src/main/resources/templates/home/newSchedule.html
Labels: enhancement

#71 fix/70-read, create, modify done
  build.gradle
  src/main/java/GHOST/sk_ghost/controller/Admin.java
  src/main/java/GHOST/sk_ghost/controller/Home.java
  src/main/resources/static/JavaScript/adminDateSearch.js
  src/main/resources/static/JavaScript/createCardStored.js
  src/main/resources/static/JavaScript/createSchedule.js
  src/main/resources/static/JavaScript/createScheduleCard.js
  src/main/resources/static/JavaScript/loginWithKakaoForAdmin.js
  src/main/resources/static/JavaScript/modifyBtn.js
  src/main/resources/static/JavaScript/modifyScheduleFunction.js
  src/main/resources/static/JavaScript/newScheduleFunction.js
  src/main/resources/static/JavaScript/savedwithSession.js
  src/main/resources/static/JavaScript/scheduleCard.js
  src/main/resources/templates/home/400.html
  src/main/resources/templates/home/admin.html
  src/main/resources/templates/home/index.html
  src/main/resources/templates/home/modifySchedule.html
Labels: bug, enhancement, New, refactoring, test, fix

#76 feat/75-modify & creation
  src/main/java/GHOST/sk_ghost/controller/Admin.java
  src/main/java/GHOST/sk_ghost/controller/Home.java
  src/main/java/GHOST/sk_ghost/dao/V1Dao.java
  src/main/java/GHOST/sk_ghost/service/V1service.java
  src/main/resources/static/JavaScript/modifyCancelBtn.js
  src/main/resources/static/JavaScript/modifySaveBtn.js
  src/main/resources/static/JavaScript/modifyScheduleFunction.js
  src/main/resources/static/JavaScript/tt.js
  src/main/resources/templates/home/modifySchedule.html
Labels: bug, enhancement, New, refactoring, fix

#82 refac/81-Cards layout
  src/main/resources/static/JavaScript/deleteScheduleFunction.js
  src/main/resources/static/JavaScript/modifyScheduleFunction.js
  src/main/resources/static/JavaScript/scheduleCard.js
  src/main/resources/static/css/admin/admin.css
  src/main/resources/static/css/admin/deleteAdmin.css
  src/main/resources/static/css/admin/modiyAdmin.css
  src/main/resources/static/css/admin/newAdmin.css
Labels: bug, refactoring, fix

#88 fix/86-add wms function and insert bug
  src/main/java/GHOST/sk_ghost/controller/Admin.java
  src/main/java/GHOST/sk_ghost/controller/Home.java
  src/main/resources/static/JavaScript/createCardStored.js
  src/main/resources/static/JavaScript/createSchedule.js
  src/main/resources/static/JavaScript/modifyCancelBtn.js
  src/main/resources/static/JavaScript/modifySaveBtn.js
  src/main/resources/static/JavaScript/modifyScheduleFunction.js
  src/main/resources/static/JavaScript/newScheduleFunction.js
  src/main/resources/static/JavaScript/scheduleCard.js
  src/main/resources/static/JavaScript/tt.js
  src/main/resources/static/css/admin/modiyAdmin.css
  src/main/resources/templates/home/400.html
  src/main/resources/templates/home/404.html
  src/main/resources/templates/home/admin.html
  src/main/resources/templates/home/index.html
  src/main/resources/templates/home/modifySchedule.html
  src/main/resources/templates/home/newSchedule.html
Labels: bug, enhancement, refactoring, fix

#97 fix/96-rest
  src/main/java/GHOST/sk_ghost/controller/Admin.java
  src/main/resources/static/JavaScript/adminDateSearch.js
  src/main/resources/static/JavaScript/createSchedule.js
  src/main/resources/static/JavaScript/loginOPWithKakao.js
  src/main/resources/static/JavaScript/loginWithKakaoForAdmin.js
  src/main/resources/static/JavaScript/modifyBtn.js
  src/main/resources/static/JavaScript/modifySaveBtn.js
  src/main/resources/static/JavaScript/modifyScheduleFunction.js
  src/main/resources/static/JavaScript/newScheduleFunction.js
  src/main/resources/templates/home/admin.html
Labels: bug, refactoring, test, fix

#98 fix/github_merge
  src/main/resources/static/JavaScript/deleteSaveBtn.js
  src/main/resources/static/JavaScript/deleteScheduleCard.js
  src/main/resources/static/JavaScript/deleteScheduleFunction.js
  src/main/resources/static/css/admin/deleteAdmin.css
Labels: fix

#103 Fix update and delete mapper
  src/main/java/GHOST/sk_ghost/controller/Admin.java
  src/main/java/GHOST/sk_ghost/dao/V1Dao.java
  src/main/java/GHOST/sk_ghost/service/V1service.java
  src/main/resources/sqlmapper/V1sql.xml
  src/main/resources/static/JavaScript/adminDateSearch.js
  src/main/resources/static/JavaScript/createSchedule.js
  src/main/resources/static/JavaScript/modifySaveBtn.js
  src/main/resources/static/css/admin/admin.css
  src/main/resources/templates/home/admin.html
Labels: enhancement, refactoring, test, fix

#109 feat/106-delete
  src/main/java/GHOST/sk_ghost/controller/Admin.java
  src/main/java/GHOST/sk_ghost/controller/Home.java
  src/main/java/GHOST/sk_ghost/dao/V1Dao.java
  src/main/java/GHOST/sk_ghost/service/V1service.java
  src/main/resources/sqlmapper/V1sql.xml
  src/main/resources/static/JavaScript/createSchedule.js
  src/main/resources/static/JavaScript/deleteCancelBtn.js
  src/main/resources/static/JavaScript/deleteSaveBtn.js
  src/main/resources/static/JavaScript/deleteScheduleCard.js
  src/main/resources/static/JavaScript/deleteScheduleFunction.js
  src/main/resources/static/JavaScript/modifySaveBtn.js
  src/main/resources/static/JavaScript/scheduleCard.js
  src/main/resources/static/css/admin/admin.css
  src/main/resources/static/css/admin/deleteAdmin.css
Labels: bug, enhancement, New, refactoring, test, fix

#115 fix/113-network
  src/main/java/GHOST/sk_ghost/controller/Admin.java
  src/main/java/GHOST/sk_ghost/controller/Home.java
  src/main/java/GHOST/sk_ghost/service/V1service.java
  src/main/resources/static/JavaScript/createCardStored.js
  src/main/resources/static/JavaScript/createSchedule.js
  src/main/resources/static/JavaScript/createScheduleCard.js
  src/main/resources/static/JavaScript/deleteSaveBtn.js
  src/main/resources/static/JavaScript/deleteScheduleCard.js
  src/main/resources/static/JavaScript/modifySaveBtn.js
  src/main/resources/static/JavaScript/newScheduleFunction.js
  src/main/resources/static/JavaScript/savedwithSession.js
  src/main/resources/static/JavaScript/scheduleCard.js
  src/main/resources/static/css/OP/OP.css
  src/main/resources/static/css/admin/admin.css
  src/main/resources/static/css/admin/deleteAdmin.css
  src/main/resources/static/css/admin/modiyAdmin.css
  src/main/resources/static/css/admin/newAdmin.css
  src/main/resources/static/css/login/login.css
  src/main/resources/templates/home/OP.html
  src/main/resources/templates/home/admin.html
  src/main/resources/templates/home/index.html
  src/main/resources/templates/home/newSchedule.html
Labels: bug, refactoring, test, fix

#123 fix/122-OP
  src/main/java/GHOST/sk_ghost/controller/Home.java
  src/main/java/GHOST/sk_ghost/dao/V1Dao.java
  src/main/java/GHOST/sk_ghost/dto/OP/AdminShiftParam.java
  src/main/java/GHOST/sk_ghost/service/V1service.java
  src/main/resources/sqlmapper/V1sql.xml
  src/main/resources/static/JavaScript/getNewYorkTime.js
  src/main/resources/static/JavaScript/isCurrentTimeInDayRange.js
  src/main/resources/static/JavaScript/isCurrentTimeInEveningRange.js
  src/main/resources/static/JavaScript/isCurrentTimeInNightRange.js
  src/main/resources/static/JavaScript/sendFriends.js
  src/main/resources/static/JavaScript/sendToMe.js
  src/main/resources/templates/home/OP.html
Labels: bug, enhancement, refactoring, test, fix

#125 fix/124-fetch
  src/main/resources/static/JavaScript/adminDateSearch.js
  src/main/resources/static/JavaScript/createSchedule.js
  src/main/resources/static/JavaScript/deleteScheduleFunction.js
  src/main/resources/static/JavaScript/getCurrEndDate.js
  src/main/resources/static/JavaScript/getCurrentDate.js
  src/main/resources/static/JavaScript/getDates.js
  src/main/resources/static/JavaScript/modifySaveBtn.js
  src/main/resources/static/JavaScript/modifyScheduleFunction.js
  src/main/resources/static/JavaScript/newScheduleFunction.js
  src/main/resources/static/JavaScript/sendFriends.js
  src/main/resources/static/css/login/login.css
  src/main/resources/templates/home/400.html
  src/main/resources/templates/home/404.html
  src/main/resources/templates/home/admin.html
  src/main/resources/templates/home/deleteSchedule.html
  src/main/resources/templates/home/modifySchedule.html
  src/main/resources/templates/home/newSchedule.html
Labels: bug, refactoring, test, fix

#128 Dev
  build.gradle
  src/main/java/GHOST/sk_ghost/common/CertificationNumber.java
  src/main/java/GHOST/sk_ghost/config/EmailConfig.java
  src/main/java/GHOST/sk_ghost/controller/Admin.java
  src/main/java/GHOST/sk_ghost/controller/Email.java
  src/main/java/GHOST/sk_ghost/controller/Home.java
  src/main/java/GHOST/sk_ghost/dao/V1Dao.java
  src/main/java/GHOST/sk_ghost/dto/EmailRequestDto.java
  src/main/java/GHOST/sk_ghost/dto/LoginDto/InsertNewUser.java
  src/main/java/GHOST/sk_ghost/dto/LoginDto/UserNameJudgement.java
  src/main/java/GHOST/sk_ghost/dto/OP/AdminShiftParam.java
  src/main/java/GHOST/sk_ghost/service/EmailService.java
  src/main/java/GHOST/sk_ghost/service/V1service.java
  src/main/java/GHOST/sk_ghost/validatior/Validatior.java
  src/main/resources/application.properties
  src/main/resources/sqlmapper/V1sql.xml
  src/main/resources/static/JavaScript/adminDateSearch.js
  src/main/resources/static/JavaScript/createSchedule.js
  src/main/resources/static/JavaScript/createScheduleCard.js
  src/main/resources/static/JavaScript/deleteCancelBtn.js
  src/main/resources/static/JavaScript/deleteSaveBtn.js
  src/main/resources/static/JavaScript/deleteScheduleFunction.js
  src/main/resources/static/JavaScript/emailAuth.js
  src/main/resources/static/JavaScript/emailSubmit.js
  src/main/resources/static/JavaScript/getCurrEndDate.js
  src/main/resources/static/JavaScript/getCurrentDate.js
  src/main/resources/static/JavaScript/getDates.js
  src/main/resources/static/JavaScript/getNewYorkTime.js
  src/main/resources/static/JavaScript/isCurrentTimeInDayRange.js
  src/main/resources/static/JavaScript/isCurrentTimeInEveningRange.js
  src/main/resources/static/JavaScript/isCurrentTimeInNightRange.js
  src/main/resources/static/JavaScript/joinFunction.js
  src/main/resources/static/JavaScript/loginOPWithKakao.js
  src/main/resources/static/JavaScript/loginWithKakaoForAdmin.js
  src/main/resources/static/JavaScript/modifyCancelBtn.js
  src/main/resources/static/JavaScript/modifySaveBtn.js
  src/main/resources/static/JavaScript/modifyScheduleFunction.js
  src/main/resources/static/JavaScript/newScheduleFunction.js
  src/main/resources/static/JavaScript/questionFunction.js
  src/main/resources/static/JavaScript/savedwithSession.js
  src/main/resources/static/JavaScript/sendFriends.js
  src/main/resources/static/JavaScript/sendToMe.js
  src/main/resources/static/JavaScript/signUp.js
  src/main/resources/static/JavaScript/tt.js
  src/main/resources/static/JavaScript/unlinkWithKakao.js
  src/main/resources/static/JavaScript/userInfoChangeFuntion.js
  src/main/resources/static/css/images/Ghost2.png
  src/main/resources/static/css/login/emailAuth.css
  src/main/resources/static/css/login/emailSignUp.css
  src/main/resources/static/css/login/emailSubmit.css
  src/main/resources/static/css/login/login.css
  src/main/resources/templates/home/400.html
  src/main/resources/templates/home/404.html
  src/main/resources/templates/home/OP.html
  src/main/resources/templates/home/admin.html
  src/main/resources/templates/home/deleteSchedule.html
  src/main/resources/templates/home/emailAuthTemp.html
  src/main/resources/templates/home/index.html
  src/main/resources/templates/home/modifySchedule.html
  src/main/resources/templates/home/newSchedule.html
Labels: distribution

#132 Fix/131 join
  build.gradle
  src/main/java/GHOST/sk_ghost/controller/Email.java
  src/main/java/GHOST/sk_ghost/controller/Home.java
  src/main/java/GHOST/sk_ghost/dao/V1Dao.java
  src/main/java/GHOST/sk_ghost/service/EmailService.java
  src/main/java/GHOST/sk_ghost/service/V1service.java
  src/main/java/GHOST/sk_ghost/validatior/Validatior.java
  src/main/resources/application.properties
  src/main/resources/sqlmapper/V1sql.xml
  src/main/resources/static/JavaScript/emailAuth.js
  src/main/resources/static/JavaScript/emailSubmit.js
  src/main/resources/static/JavaScript/joinFunction.js
  src/main/resources/static/JavaScript/loginOPWithKakao.js
  src/main/resources/static/JavaScript/loginWithKakaoForAdmin.js
  src/main/resources/static/JavaScript/questionFunction.js
  src/main/resources/static/JavaScript/signUp.js
  src/main/resources/static/JavaScript/userInfoChangeFuntion.js
  src/main/resources/static/css/login/changeInfo.css
  src/main/resources/static/css/login/emailAuth.css
  src/main/resources/static/css/login/emailSignUp.css
  src/main/resources/static/css/login/emailSubmit.css
  src/main/resources/static/css/login/login.css
  src/main/resources/templates/home/admin.html
  src/main/resources/templates/home/emailAuthTemp.html
  src/main/resources/templates/home/index.html
Labels: bug, enhancement, New, refactoring, test, fix

#137 refac/134-all
  src/main/java/GHOST/sk_ghost/config/JasyptConfig.java
  src/main/resources/static/JavaScript/adminDateSearch.js
  src/main/resources/static/JavaScript/createCardStored.js
  src/main/resources/static/JavaScript/createSchedule.js
  src/main/resources/static/JavaScript/deleteCancelBtn.js
  src/main/resources/static/JavaScript/deleteSaveBtn.js
  src/main/resources/static/JavaScript/deleteScheduleCard.js
  src/main/resources/static/JavaScript/deleteScheduleFunction.js
  src/main/resources/static/JavaScript/emailAuth.js
  src/main/resources/static/JavaScript/endReport.js
  src/main/resources/static/JavaScript/isCurrentTimeInNightRange.js
  src/main/resources/static/JavaScript/loginAram.js
  src/main/resources/static/JavaScript/loginOPWithKakao.js
  src/main/resources/static/JavaScript/loginWithKakaoForAdmin.js
  src/main/resources/static/JavaScript/modifyBtn.js
  src/main/resources/static/JavaScript/modifyCancelBtn.js
  src/main/resources/static/JavaScript/modifySaveBtn.js
  src/main/resources/static/JavaScript/modifyScheduleFunction.js
  src/main/resources/static/JavaScript/newScheduleFunction.js
  src/main/resources/static/JavaScript/questionFunction.js
  src/main/resources/static/JavaScript/savedwithSession.js
  src/main/resources/static/JavaScript/scheduleCard.js
  src/main/resources/static/JavaScript/sendFriends.js
  src/main/resources/static/JavaScript/sendToMe.js
  src/main/resources/static/JavaScript/sendToMe_Origin.js
  src/main/resources/static/css/OP/OP.css
  src/main/resources/static/css/admin/admin.css
  src/main/resources/static/css/admin/deleteAdmin.css
  src/main/resources/static/css/admin/modiyAdmin.css
  src/main/resources/static/css/admin/newAdmin.css
  src/main/resources/static/css/login/emailSignUp.css
  src/main/resources/static/css/login/login.css
  src/main/resources/templates/home/OP.html
Labels: bug, enhancement, wontfix, refactoring, test, fix

#139 feat/138-Enhance edit profile functions
  src/main/java/GHOST/sk_ghost/controller/Home.java
  src/main/java/GHOST/sk_ghost/dao/V1Dao.java
  src/main/java/GHOST/sk_ghost/service/V1service.java
  src/main/resources/sqlmapper/V1sql.xml
  src/main/resources/static/JavaScript/userInfoChangeFuntion.js
  src/main/resources/static/css/login/changeInfo.css
Labels: bug, enhancement, refactoring, test, fix

#141 bug/140-join
  src/main/resources/static/JavaScript/deleteScheduleFunction.js
  src/main/resources/static/JavaScript/deleteSession.js
  src/main/resources/static/JavaScript/emailAuth.js
  src/main/resources/static/JavaScript/emailSubmit.js
  src/main/resources/static/JavaScript/endReport.js
  src/main/resources/static/JavaScript/joinFunction.js
  src/main/resources/static/JavaScript/loginOPWithKakao.js
  src/main/resources/static/JavaScript/loginWithKakaoForAdmin.js
  src/main/resources/static/JavaScript/modifyScheduleFunction.js
  src/main/resources/static/JavaScript/questionFunction.js
  src/main/resources/static/JavaScript/sendFriends.js
  src/main/resources/static/JavaScript/sendToMe.js
  src/main/resources/static/JavaScript/signUp.js
  src/main/resources/static/JavaScript/unlinkWithKakao.js
  src/main/resources/static/JavaScript/userInfoChangeFuntion.js
  src/main/resources/templates/home/OP.html
  src/main/resources/templates/home/admin.html
  src/main/resources/templates/home/deleteSchedule.html
  src/main/resources/templates/home/modifySchedule.html
  src/main/resources/templates/home/newSchedule.html
Labels: bug, wontfix, refactoring, test, fix

#142 Dev
  src/main/java/GHOST/sk_ghost/config/JasyptConfig.java
  src/main/java/GHOST/sk_ghost/controller/Home.java
  src/main/java/GHOST/sk_ghost/dao/V1Dao.java
  src/main/java/GHOST/sk_ghost/dto/LoginDto/UpdateUser.java
  src/main/java/GHOST/sk_ghost/service/V1service.java
  src/main/resources/sqlmapper/V1sql.xml
  src/main/resources/static/JavaScript/adminDateSearch.js
  src/main/resources/static/JavaScript/createCardStored.js
  src/main/resources/static/JavaScript/createSchedule.js
  src/main/resources/static/JavaScript/deleteCancelBtn.js
  src/main/resources/static/JavaScript/deleteSaveBtn.js
  src/main/resources/static/JavaScript/deleteScheduleCard.js
  src/main/resources/static/JavaScript/deleteScheduleFunction.js
  src/main/resources/static/JavaScript/deleteSession.js
  src/main/resources/static/JavaScript/emailAuth.js
  src/main/resources/static/JavaScript/emailSubmit.js
  src/main/resources/static/JavaScript/endReport.js
  src/main/resources/static/JavaScript/isCurrentTimeInNightRange.js
  src/main/resources/static/JavaScript/joinFunction.js
  src/main/resources/static/JavaScript/loginAram.js
  src/main/resources/static/JavaScript/loginOPWithKakao.js
  src/main/resources/static/JavaScript/loginWithKakaoForAdmin.js
  src/main/resources/static/JavaScript/modifyBtn.js
  src/main/resources/static/JavaScript/modifyCancelBtn.js
  src/main/resources/static/JavaScript/modifySaveBtn.js
  src/main/resources/static/JavaScript/modifyScheduleFunction.js
  src/main/resources/static/JavaScript/newScheduleFunction.js
  src/main/resources/static/JavaScript/questionFunction.js
  src/main/resources/static/JavaScript/savedwithSession.js
  src/main/resources/static/JavaScript/scheduleCard.js
  src/main/resources/static/JavaScript/sendFriends.js
  src/main/resources/static/JavaScript/sendToMe.js
  src/main/resources/static/JavaScript/sendToMe_Origin.js
  src/main/resources/static/JavaScript/signUp.js
  src/main/resources/static/JavaScript/unlinkWithKakao.js
  src/main/resources/static/JavaScript/userInfoChangeFuntion.js
  src/main/resources/static/css/OP/OP.css
  src/main/resources/static/css/admin/admin.css
  src/main/resources/static/css/admin/deleteAdmin.css
  src/main/resources/static/css/admin/modiyAdmin.css
  src/main/resources/static/css/admin/newAdmin.css
  src/main/resources/static/css/login/changeInfo.css
  src/main/resources/static/css/login/emailSignUp.css
  src/main/resources/static/css/login/login.css
  src/main/resources/templates/home/OP.html
  src/main/resources/templates/home/admin.html
  src/main/resources/templates/home/deleteSchedule.html
  src/main/resources/templates/home/modifySchedule.html
  src/main/resources/templates/home/newSchedule.html
Labels: bug, help wanted, wontfix, refactoring, test, fix

#149 Dev
  build.gradle
  src/main/java/GHOST/sk_ghost/controller/Admin.java
  src/main/java/GHOST/sk_ghost/controller/Home.java
  src/main/java/GHOST/sk_ghost/service/V1service.java
  src/main/resources/static/css/admin/admin.css
  src/main/resources/static/css/admin/deleteAdmin.css
  src/main/resources/static/css/admin/modiyAdmin.css
  src/main/resources/static/css/admin/newAdmin.css
Labels: distribution, test
